### ISSUE TITLE
Having trouble importing deepmerge with Webpack

### ISSUE THREAD

**Issue by GioSensation** [KyleAMathews/deepmerge#87] opened 2017-11-29 13:06 UTC
When importing deepmerge with `import * as merge from 'deepmerge';` throws `Error: merge is not a function` in the app, while the tests run just fine.

When importing with `import merge from `deepmerge;`, the app works fine, but the jest tests throw `TypeError: deepmerge_1.default is not a function`.

I have temporarily patched the issue in my code with an `if/else` block to reassign the correct function to the variable, but I feel there must be a better way.

Maybe jest is misconfigured. Has anyone ever encountered a similar issue or can provide a configuration template that is proven to be working?

This describes a similar issue to what I am experiencing https://github.com/aurelia/skeleton-navigation/issues/606, though I am not using Aurelia, nor Moment. It just seems like the same _kind_ of problem.

--------

**Node version**: 8.6.0
**NPM version**: 5.5.1
**Webpack version**: 3.6.0
**Typescript version**: 2.5.3
**deepmerge version**: 2.0.1

-------

tsconfig.json

```javascript
{
  "compilerOptions": {
    "outDir": "./dist/",
    "sourceMap": true,
    "noImplicitAny": false,
    "module": "commonjs",
    "target": "es5",
    "lib": ["es7", "es2017", "dom"],
    "jsx": "preserve",
    "allowJs": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "**/*.test.ts"]
}
```

-------

.babelrc

```javascript
{
  "presets": ["env", "react"],
  "plugins": [
    "react-css-modules"
  ]
}
```

-------

jest.config.json

```javascript
{
  "transform": {
    ".(ts|tsx)": "<rootDir>/node_modules/ts-jest/preprocessor.js"
  },
  "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$",
  "moduleFileExtensions": ["ts", "tsx", "js", "jsx", "json"]
}
```

**Comment by TehShrike** [comment] 2017-11-29 15:00
`import * as merge` is incorrect - assuming your bundler is [picking up the ES module](https://github.com/KyleAMathews/deepmerge/blob/3ab89f2d2c938fc2e045c4ba822da0ffb81e4891/package.json#L20), then you're loading the [ESM build of the package](https://unpkg.com/deepmerge@2.0.1/dist/es.js), which only exposes a default export.  `import merge from 'deepmerge'` is correct.

I would guess that there is different bundling/module loading happening between typescript and jest.  I'm not familiar with either of them, but my clue to you is to make sure that they're both either paying attention to the [`module` field in deepmerge's package.json](https://github.com/rollup/rollup/wiki/pkg.module) (if you want them to pick up the ESM version), or they're both ignoring it (if you want them to pick up the UMD version).

**Comment by richardschneider** [comment] 2017-12-06 04:32
I'm not using TypeScript, just JS on the browser and on node. v2.0.2 works on node, but fails with the error on a browser.  Reverting to v1.5.2 works on both environments.

**Comment by TehShrike** [comment] 2017-12-06 05:44
@richardschneider What bundler are you using?  What is the error message?

**Comment by richardschneider** [comment] 2017-12-06 07:54
@TehShrike I'm using `webpack`. The error is `TypeError: deepmerge is not a function`.

See code at https://github.com/richardschneider/ipfs-encryption/blob/master/src/keychain.js#L80

**Comment by TehShrike** [comment] 2017-12-06 15:14
I couldn't find any webpack config in that repo, but I'm no Webpack expert anyways.

In any case, I can guess at the problem pretty easily - your Webpack is configured to load in the [ESM module](https://github.com/KyleAMathews/deepmerge/blob/3ab89f2d2c938fc2e045c4ba822da0ffb81e4891/package.json#L20), and is probably exposing default exports as a `default` property instead of the object you get when you `require`.

There are lots of ways you could fix this - you could `const deepmerge = require('deepmerge').default`, or you could switch your project over to using ES modules and do `import deepmerge from 'deepmerge'`, or you could configure Webpack to ignore the `module` setting in package.json and just pull in `main`, since it looks like you don't care about ES modules, or you could configure Webpack to return the default export as the object returned by `require` instead of returning `{ default: deepmerge }`.

If you want your un-built code to work in node.js, I'm guessing you'll want to do one of the two latter options.

**Comment by GioSensation** [comment] 2017-12-08 09:30
Just to update the issue, I have solved this by importing explicitly the file I want, `es.js`, like this:

```javascript
import merge from '../node_modules/deepmerge/dist/es.js';
```

I am not particularly happy about this, because if the name or path to the file change, the import will break. It is still the best solution I could find.

I have opened an [issue on StackOverflow](https://stackoverflow.com/questions/47590090/jest-and-es2015-imports-make-jest-respect-the-pkg-module-declaration-in-package) to see if anybody had any insights to offer, but no answers thus far.

I guess you can close this issue if you have nothing to add.

Thanks.

**Comment by TehShrike** [comment] 2017-12-08 14:33
@GioSensation You still haven't responded to my earlier message - it looks like you have two bundler environments, and they're both resolving modules differently.  This doesn't have anything to do with this package using Rollup to bundle, it has to do with your bundlers respecting the `main` vs `module` fields in package.json.

A quick search of issues in the Jest repo turns up this: https://github.com/facebook/jest/issues/2702

It looks like somebody in that thread figured out a workaround for Jest.

**Comment by GioSensation** [comment] 2017-12-11 12:17
Thanks. I will look into it and wait for the Jest team to integrate that pull request.

Cheers!

**Comment by Tarnadas** [comment] 2018-01-29 22:23
Could this be reopenend?
The problem still persists and I don't feel like `const merge = require('deepmerge').default` is an ideal solution.
My app won't compile when I use `import merge from 'deepmerge'` with TypeScript 2.8 and Webpack 3.10.0, so it's not just affecting jest tests.

**Comment by TehShrike** [comment] 2018-01-29 22:38
As long as your bundler respects the [`module` field in package.json](https://github.com/rollup/rollup/wiki/pkg.module) (which [webpack claims to support](https://github.com/webpack/webpack/issues/1979#issuecomment-241105288)), everything should work fine.

The package.json's `module` field points to [es.js](https://unpkg.com/deepmerge@2.0.1/dist/es.js), which is a traditional ES module that exports a single default.

The package.json's `main` field points to [umd.js](https://unpkg.com/deepmerge@2.0.1/dist/umd.js), which is a bog-standard UMD file compatible with CommonJS and AMD bundlers.

Which one of those do you want your bundler to pick up?  That is up to your project's configuration.

As far as I know, deepmerge's two entry points are the epitome of bundler-friendliness.  Any issues should be the result of a misconfiguration or a bug in the bundler that you're using.

I don't know if it's a configuration issue or a bug, but it sounds like some combination of Typescript + Webpack has an issue out of the box.

**Comment by leoalves** [comment] 2018-02-01 03:01
@Tarnadas 
The issue with typescript is that the types from @types/deepmerge is wrong.

If you edit the file index.d.ts from node_modules/@types/deepmerge and change the export from 
`export = deepmerge; `
to 
`export default deepmerge` 
you can import it as
`import deepmerge from 'deepmerge'`

If you want to import as 
`import merge from 'deepmerge'`
you need to replace all references in that file from deepmerge to merge.

I am not sure if the typings reflect the most up to date version of the library.  There is only one method that I use and for that one is working.

**Comment by TehShrike** [comment] 2018-02-01 03:16
ooooh, is that why people are having difficulty with TypeScript?

Where are people getting these types from?  Can somebody update them?

Does Typescript pull from `module` by default?

**Comment by leoalves** [comment] 2018-02-01 04:23
There is a single repository that most common libraries types are there. It's mostly updated and maintainted by the community. https://github.com/DefinitelyTyped/DefinitelyTyped.  The issue is that a lot of times they are not up to date with the library and this can cause issues when compiling. 

In this case the problem is more with how TypeScript import works. TypeScript threats CommonJS/AMD/UMD modules in the same way as ES6 modules. When you do `import * as merge from 'deepmerge'` is the same as `merge = require('deepmerge')`. This doesn't work for your library.  

The other way would be `import merge from 'deepmerge'` which is the same as `merge = require('deepmerge').default`.  This would work for your library. 

But the typescript compiler has a configuration option called noImplicitAny. If this option is enabled the typescript does not compile if the type is any. That's the case for your library since you don't have typings.  

This option is not enabled by default, but since @Tarnadas was complaining about compiling issues, I figured that this was enabled for him. I also assumed he was using the types from DefinelyTyped. That's why I suggested changing that file.

**Comment by pacey** [comment] 2018-02-01 11:44
I'm having this issue too but deepmerge is being used by a transitive dependency so I can't change the import/require of the function. Any ideas?

**Comment by TehShrike** [comment] 2018-02-01 15:20
I'm at a disadvantage here because I'm not familiar with TypeScript's module resolution.  I'm also not terribly motivated to spend a day learning about it to fix this issue :-x

deepmerge offers a good import experience for both CommonJS consumers (setting `module.exports` to a single function) and ES Module consumers (exporting the function as the default export).

I don't see any reason to change that in order to facilitate TypeScript.  Besides, as more modules start shipping ES Modules, this problem will keep happening to TypeScript users.

That said, it would be nice to know how to fix it.

Are the [typings on DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/deepmerge/index.d.ts) correct?  Could they be changed to fix the issue?

Should an issue be opened on TypeScript?  A quick search turns up at least a couple issues related to CommonJS/ESM interop ({#3337](https://github.com/Microsoft/TypeScript/issues/3337), [#2719](https://github.com/Microsoft/TypeScript/issues/2719)), there may be some clues in there.

@pacey, does the library that is consuming deepmerge use the `require` or `import` syntax?  Does the issue only happen when `require` is used?  How does TypeScript decide whether to use `main` versus `module`?

If there is some way to work around this TypeScript issue by fiddling with Webpack/Babel config, it would be good to get it on record here.

**Comment by TehShrike** [comment] 2018-02-01 15:25
It may also just be an issue with Webpack. https://github.com/webpack/webpack/issues/5756

**Comment by pacey** [comment] 2018-02-01 17:12
Yeah it's quite possible to just be a Webpack issue @TehShrike. I'll try and get webpack/webpack#5756 resurrected!

**Comment by TehShrike** [comment] 2018-02-01 17:31
@pacey can you make a bare-bones reproduction in a public repository that is just a single-file app that imports deepmerge and gets bundled with webpack?

**Comment by dsole** [comment] 2018-02-09 04:21
I'm fairly sure the typings in Definitely Typed are incorrect, and should be declaring a default import.

The typing currently has
`export = deepmerge;`
should be 
`export default deepmerge;`

In your TS script you would then use
`import deepmerge from "deepmerge";`
and call it as normal
`const result = deepmerge(x, y);`

**Comment by perry-mitchell** [comment] 2018-02-26 07:00
I'm also getting this issue, but not with typescript: #97

**Comment by TehShrike** [comment] 2018-02-26 19:22
I opened an issue with Webpack: https://github.com/webpack/webpack/issues/6584

**Comment by jonmanzo** [comment] 2018-03-01 16:24
FWIW I was able to work around setting a resolve alias in the webpack config

```
alias: {
      deepmerge$: path.resolve(__dirname, 'node_modules/deepmerge/dist/umd.js'),
    }
```

**Comment by TehShrike** [comment] 2018-03-01 17:45
Cool - that's probably worth putting into the readme until the Webpack issue is fixed.

**Comment by tomwayson** [comment] 2018-03-29 15:40
I was also having this problem w/ Jest (also using TypeScript, but using Rollup to bundle my library), and I came up w/ a different solution that might work for other Jest users until https://github.com/facebook/jest/pull/2704 is merged/released. I created a manual mock that `require()`s deepmerge and then `exports` it out:

```ts
// __mocks__/deepmerge.ts 
// (where __mocks__ is a sibling to node_modules)

import deepmerge = require('deepmerge')
export default function merge(...args) {
  return deepmerge(...args)
}
```

FYI - I'm not using the DefinitelyTyped typings, so ¯\_(ツ)_/¯

FWIW, @TehShrike I _think_ you're doing everything right on the `package.main`/`package.module` front. I think my problems would be solved if Jest was able to respect the `module` field.

**Comment by zackypick** [comment] 2018-04-20 07:17
if you're just extending simple object you can quickly roll your own solution, e.g:

```
export const deepObjectExtend = function (target: any, source: any) {

    for (let prop in source) {
        if (prop in target) {
            deepObjectExtend(target[prop], source[prop]);
        } else {
            target[prop] = source[prop];
        }
    }

    return target;
};
```

**Comment by Xiaosha61** [comment] 2018-05-25 11:17
'is-mergeable-object' should be a dependency not dev-dep, shouldn't it?

**Comment by TehShrike** [comment] 2018-05-25 17:56
The output is [bundled with rollup](https://github.com/KyleAMathews/deepmerge/blob/master/package.json#L25) before deploying, so `is-mergeable-object`'s code is included in the deployed version.  You can see `isMergeableObject` inlined in the version deployed to npm [on unpkg](https://unpkg.com/deepmerge@2.1.0/dist/umd.js).

**Comment by mesqueeb** [comment] 2018-06-28 04:49
I have a similar problem where it's looking in all places, just not the node_modules:
```bash
ERROR in /Users/-----/.ghq/github.com/mesqueeb/VuexEasyFirestore/src/utils/setDefaultValues.js
Module not found: Error: Can't resolve 'deepmerge' in '/Users/-----/.ghq/github.com/mesqueeb/VuexEasyFirestore/src/utils'
 @ /Users/-----/.ghq/github.com/mesqueeb/VuexEasyFirestore/src/utils/setDefaultValues.js 1:0-29 11:9-14
 @ /Users/-----/.ghq/github.com/mesqueeb/VuexEasyFirestore/src/module/actions.js
 @ /Users/-----/.ghq/github.com/mesqueeb/VuexEasyFirestore/src/module/index.js
 @ /Users/-----/.ghq/github.com/mesqueeb/VuexEasyFirestore/src/index.js
 @ ./src/store/store.js
 @ ./src/store/index.js
```

**Comment by TehShrike** [comment] 2018-06-28 05:37
huh, that's super-weird.  That does seem like a separate issue, since it just has to do with resolving the package, instead of returning the CJS versus ESM version of the package.

**Comment by mesqueeb** [comment] 2018-06-28 07:41
@TehShrike 
Yeah, I'm not sure what the problem is. Maybe because I'm linking with `npm link` to this seperate package I'm working on where I use the `deepmerge`. However, other npm modules work fine there...

I also tried editing the `main` prop in the package.json of deepmerge to the es version. Didn't work.

Once I am done developing, & rollup my package, i'll let you know if anything has changed.

**Comment by mesqueeb** [comment] 2018-06-30 03:16
@TehShrike 
I was able to find exactly what the problem was.

I was working on an npm package which had recently added `deepmerge` as a dependency.
However through `npm link` I was testing my npm package inside another package which I was doing a webpack dev hot reload on.

Then it hit me. if I try to `npm i deepmerge` in this other package it might work!
And yes it did!

To all people trying to test `deepmerge` inside another package which is being linked to yet another using webpack hot reload, **don't forget to `npm i deepmerge` in the package having the webpack hot reload enabled.**

**Comment by msssk** [comment] 2018-09-28 04:09
The [DefinitelyTyped typedefs](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/deepmerge/index.d.ts) are bad. I uninstalled them and added the following to my project and it works:

```typescript
declare module 'deepmerge' {
	function deepmerge<T>(x: Partial<T>, y: Partial<T>, options?: deepmerge.Options): T;
	function deepmerge<T1, T2>(x: Partial<T1>, y: Partial<T2>, options?: deepmerge.Options): T1 & T2;

	namespace deepmerge {
		export interface Options {
			arrayMerge?(target: any[], source: any[], options?: Options): any[];
			clone?: boolean;
			isMergeableObject?(value: object): boolean;
		}

		export function all<T>(objects: Partial<T>[], options?: Options): T;
	}

	export default deepmerge;
}
```

If you (deepmerge maintainers) are interested in fixing this within your project, you can include the above in `deepmerge/index.d.ts`. If you would rather offload the maintenance of TS definitions then perhaps I'll submit a PR to DefinitelyTyped (I'm not totally confident in my changes, but they at least make deepmerge basics work for me):

```typescript
import deepmerge from 'deepmerge';
const opts: deepmerge.Options;
deepmerge(x, y);
deepmerge.all(x, y);
```

**Comment by TehShrike** [comment] 2018-09-28 13:38
I'm now open to maintaining a type definition in this project, as long as there is a test that can be added to the npm run scripts, similar to the [DefinitelyTyped tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/deepmerge/deepmerge-tests.ts).

A PR to this repo would be appreciated!

**Comment by sveyret** [comment] 2018-10-24 19:41
In the  last delivery (2.2.1) a correction was made on the index.d.ts which is making the Typescript import impossible again… You should keep the `export default` in order to be able to do
    import merge from 'deepmerge'
Without this, Typescript users can only do
    import * as merge from 'deepmerge'

**Comment by msssk** [comment] 2018-10-24 19:47
@sveyret 
https://github.com/KyleAMathews/deepmerge/pull/121#issuecomment-427208424

A full-TS option (with better typing as well): [`dojo/framework/util`](https://github.com/dojo/framework/blob/master/src/core/util.ts)

**Comment by TehShrike** [comment] 2018-10-24 20:29
See #124

**Comment by sveyret** [comment] 2018-10-24 20:33
OK, so this makes sense. But how should we configure Webpack, now, in order not to have the `is not a function` error? I thought the solution was to take the ES module…

**Comment by TehShrike** [comment] 2018-10-24 20:35
There's a [workaround in the readme](https://github.com/KyleAMathews/deepmerge#webpack-bug) that has worked for some people

**Comment by sveyret** [comment] 2018-10-24 20:37
OK, will try. Thank you.

**Comment by sveyret** [comment] 2018-10-25 09:02
Defining alias in Webpack is working, but just for information, modules may not be in current project directory (case of [workspaces](https://yarnpkg.com/lang/en/docs/workspaces/)) for example. So it would be better not to define absolute path in Webpack configuration. This is how I did in my project:

    alias: {
      deepmerge$: 'deepmerge/dist/umd.js',
    },

**Comment by ciekawy** [comment] 2018-10-28 15:02
I just added `deepmerge` to my Ionic/Angular TypeScript project and hit the 
```
Error:(25, 8) TS1192: Module '"node_modules/deepmerge/index"' has no default export.
```

The project have lot of external dependencies and it would be great to have this fixed regardless possible specific webpack (or other tools) limitations.

the workaround for me now is:
```
const merge = require('deepmerge');
```

**Closed** 2018-12-04 20:41 UTC
